services:
  - type: pserv 
    name: database-postgres
    env: postgres
    plan: free 

  - type: web
    name: todoapp-postgres 
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn todoapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv 
          name: database-postgres 
          property: connectionString 
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0 